services:
  mysql:
    image: mysql:8.0
    container_name: mysql_single_node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql-logs:/var/log/mysql
    command: --default-authentication-plugin=mysql_native_password
